name: 'Create a manifest list'
description: 'Create a new image based on source images with Buildx'
author: 'kphrx'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'anchor'
  color: 'blue'

# Define your inputs here.
inputs:
  annotations:
    description: 'List of annotation to set to the image'
    required: false
  dry-run:
    description: 'Dry run imagetools create'
    default: 'false'
  tags:
    description: 'List of tags'
    required: false
  github-token:
    description: 'GitHub Token used to authenticate against a repository for Git context'
    default: ${{ github.token }}

# Define your outputs here.
outputs:
  digest:
    description: 'Image digest'
  metadata:
    description: 'Build result metadata'

runs:
  using: node20
  main: dist/index.js
